#!/usr/bin/env bash
time pig -x local -p root_path=full_unibitrigrams -p input=000 -p output=001 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=001 -p output=002 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=002 -p output=003 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=003 -p output=004 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=004 -p output=005 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=005 -p output=006 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=006 -p output=007 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=007 -p output=008 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=008 -p output=009 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=009 -p output=010 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=010 -p output=011 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=011 -p output=012 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=012 -p output=013 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=013 -p output=014 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=014 -p output=015 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=015 -p output=016 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=016 -p output=017 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=017 -p output=018 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=018 -p output=019 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=019 -p output=020 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=020 -p output=021 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=021 -p output=022 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=022 -p output=023 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=023 -p output=024 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=024 -p output=025 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=025 -p output=026 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=026 -p output=027 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=027 -p output=028 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=028 -p output=029 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=029 -p output=030 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=030 -p output=031 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=031 -p output=032 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=032 -p output=033 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=033 -p output=034 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=034 -p output=035 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=035 -p output=036 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=036 -p output=037 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=037 -p output=038 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=038 -p output=039 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=039 -p output=040 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=040 -p output=041 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=041 -p output=042 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=042 -p output=043 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=043 -p output=044 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=044 -p output=045 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=045 -p output=046 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=046 -p output=047 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=047 -p output=048 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=048 -p output=049 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=049 -p output=050 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=050 -p output=051 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=051 -p output=052 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=052 -p output=053 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=053 -p output=054 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=054 -p output=055 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=055 -p output=056 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=056 -p output=057 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=057 -p output=058 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=058 -p output=059 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=059 -p output=060 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=060 -p output=061 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=061 -p output=062 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=062 -p output=063 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=063 -p output=064 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=064 -p output=065 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=065 -p output=066 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=066 -p output=067 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=067 -p output=068 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=068 -p output=069 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=069 -p output=070 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=070 -p output=071 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=071 -p output=072 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=072 -p output=073 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=073 -p output=074 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=074 -p output=075 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=075 -p output=076 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=076 -p output=077 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=077 -p output=078 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=078 -p output=079 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=079 -p output=080 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=080 -p output=081 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=081 -p output=082 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=082 -p output=083 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=083 -p output=084 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=084 -p output=085 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=085 -p output=086 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=086 -p output=087 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=087 -p output=088 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=088 -p output=089 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=089 -p output=090 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=090 -p output=091 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=091 -p output=092 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=092 -p output=093 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=093 -p output=094 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=094 -p output=095 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=095 -p output=096 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=096 -p output=097 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=097 -p output=098 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=098 -p output=099 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=099 -p output=100 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=100 -p output=101 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=101 -p output=102 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=102 -p output=103 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=103 -p output=104 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=104 -p output=105 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=105 -p output=106 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=106 -p output=107 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=107 -p output=108 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=108 -p output=109 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=109 -p output=110 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=110 -p output=111 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=111 -p output=112 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=112 -p output=113 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=113 -p output=114 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=114 -p output=115 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=115 -p output=116 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=116 -p output=117 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=117 -p output=118 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=118 -p output=119 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=119 -p output=120 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=120 -p output=121 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=121 -p output=122 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=122 -p output=123 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=123 -p output=124 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=124 -p output=125 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=125 -p output=126 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=126 -p output=127 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=127 -p output=128 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=128 -p output=129 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=129 -p output=130 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=130 -p output=131 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=131 -p output=132 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=132 -p output=133 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=133 -p output=134 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=134 -p output=135 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=135 -p output=136 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=136 -p output=137 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=137 -p output=138 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=138 -p output=139 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=139 -p output=140 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=140 -p output=141 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=141 -p output=142 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=142 -p output=143 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=143 -p output=144 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=144 -p output=145 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=145 -p output=146 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=146 -p output=147 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=147 -p output=148 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=148 -p output=149 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=149 -p output=150 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=150 -p output=151 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=151 -p output=152 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=152 -p output=153 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=153 -p output=154 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=154 -p output=155 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=155 -p output=156 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=156 -p output=157 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=157 -p output=158 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=158 -p output=159 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=159 -p output=160 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=160 -p output=161 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=161 -p output=162 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=162 -p output=163 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=163 -p output=164 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=164 -p output=165 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=165 -p output=166 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=166 -p output=167 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=167 -p output=168 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=168 -p output=169 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=169 -p output=170 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=170 -p output=171 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=171 -p output=172 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=172 -p output=173 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=173 -p output=174 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=174 -p output=175 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=175 -p output=176 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=176 -p output=177 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=177 -p output=178 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=178 -p output=179 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=179 -p output=180 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=180 -p output=181 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=181 -p output=182 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=182 -p output=183 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=183 -p output=184 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=184 -p output=185 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=185 -p output=186 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=186 -p output=187 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=187 -p output=188 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=188 -p output=189 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=189 -p output=190 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=190 -p output=191 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=191 -p output=192 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=192 -p output=193 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=193 -p output=194 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=194 -p output=195 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=195 -p output=196 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=196 -p output=197 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=197 -p output=198 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=198 -p output=199 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=199 -p output=200 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=200 -p output=201 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=201 -p output=202 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=202 -p output=203 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=203 -p output=204 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=204 -p output=205 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=205 -p output=206 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=206 -p output=207 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=207 -p output=208 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=208 -p output=209 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=209 -p output=210 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=210 -p output=211 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=211 -p output=212 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=212 -p output=213 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=213 -p output=214 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=214 -p output=215 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=215 -p output=216 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=216 -p output=217 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=217 -p output=218 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=218 -p output=219 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=219 -p output=220 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=220 -p output=221 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=221 -p output=222 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=222 -p output=223 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=223 -p output=224 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=224 -p output=225 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=225 -p output=226 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=226 -p output=227 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=227 -p output=228 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=228 -p output=229 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=229 -p output=230 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=230 -p output=231 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=231 -p output=232 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=232 -p output=233 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=233 -p output=234 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=234 -p output=235 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=235 -p output=236 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=236 -p output=237 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=237 -p output=238 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=238 -p output=239 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=239 -p output=240 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=240 -p output=241 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=241 -p output=242 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=242 -p output=243 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=243 -p output=244 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=244 -p output=245 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=245 -p output=246 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=246 -p output=247 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=247 -p output=248 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=248 -p output=249 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=249 -p output=250 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=250 -p output=251 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=251 -p output=252 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=252 -p output=253 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=253 -p output=254 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=254 -p output=255 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=255 -p output=256 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=256 -p output=257 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=257 -p output=258 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=258 -p output=259 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=259 -p output=260 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=260 -p output=261 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=261 -p output=262 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=262 -p output=263 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=263 -p output=264 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=264 -p output=265 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=265 -p output=266 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=266 -p output=267 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=267 -p output=268 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=268 -p output=269 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=269 -p output=270 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=270 -p output=271 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=271 -p output=272 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=272 -p output=273 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=273 -p output=274 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=274 -p output=275 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=275 -p output=276 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=276 -p output=277 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=277 -p output=278 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=278 -p output=279 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=279 -p output=280 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=280 -p output=281 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=281 -p output=282 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=282 -p output=283 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=283 -p output=284 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=284 -p output=285 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=285 -p output=286 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=286 -p output=287 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=287 -p output=288 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=288 -p output=289 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=289 -p output=290 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=290 -p output=291 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=291 -p output=292 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=292 -p output=293 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=293 -p output=294 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=294 -p output=295 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=295 -p output=296 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=296 -p output=297 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=297 -p output=298 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=298 -p output=299 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=299 -p output=300 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=300 -p output=301 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=301 -p output=302 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=302 -p output=303 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=303 -p output=304 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=304 -p output=305 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=305 -p output=306 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=306 -p output=307 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=307 -p output=308 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=308 -p output=309 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=309 -p output=310 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=310 -p output=311 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=311 -p output=312 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=312 -p output=313 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=313 -p output=314 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=314 -p output=315 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=315 -p output=316 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=316 -p output=317 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=317 -p output=318 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=318 -p output=319 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=319 -p output=320 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=320 -p output=321 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=321 -p output=322 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=322 -p output=323 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=323 -p output=324 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=324 -p output=325 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=325 -p output=326 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=326 -p output=327 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=327 -p output=328 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=328 -p output=329 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=329 -p output=330 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=330 -p output=331 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=331 -p output=332 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=332 -p output=333 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=333 -p output=334 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=334 -p output=335 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=335 -p output=336 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=336 -p output=337 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=337 -p output=338 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=338 -p output=339 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=339 -p output=340 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=340 -p output=341 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=341 -p output=342 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=342 -p output=343 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=343 -p output=344 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=344 -p output=345 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=345 -p output=346 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=346 -p output=347 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=347 -p output=348 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=348 -p output=349 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=349 -p output=350 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=350 -p output=351 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=351 -p output=352 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=352 -p output=353 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=353 -p output=354 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=354 -p output=355 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=355 -p output=356 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=356 -p output=357 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=357 -p output=358 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=358 -p output=359 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=359 -p output=360 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=360 -p output=361 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=361 -p output=362 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=362 -p output=363 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=363 -p output=364 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=364 -p output=365 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=365 -p output=366 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=366 -p output=367 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=367 -p output=368 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=368 -p output=369 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=369 -p output=370 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=370 -p output=371 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=371 -p output=372 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=372 -p output=373 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=373 -p output=374 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=374 -p output=375 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=375 -p output=376 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=376 -p output=377 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=377 -p output=378 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=378 -p output=379 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=379 -p output=380 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=380 -p output=381 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=381 -p output=382 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=382 -p output=383 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=383 -p output=384 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=384 -p output=385 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=385 -p output=386 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=386 -p output=387 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=387 -p output=388 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=388 -p output=389 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=389 -p output=390 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=390 -p output=391 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=391 -p output=392 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=392 -p output=393 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=393 -p output=394 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=394 -p output=395 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=395 -p output=396 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=396 -p output=397 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=397 -p output=398 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=398 -p output=399 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=399 -p output=400 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=400 -p output=401 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=401 -p output=402 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=402 -p output=403 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=403 -p output=404 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=404 -p output=405 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=405 -p output=406 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=406 -p output=407 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=407 -p output=408 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=408 -p output=409 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=409 -p output=410 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=410 -p output=411 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=411 -p output=412 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=412 -p output=413 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=413 -p output=414 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=414 -p output=415 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=415 -p output=416 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=416 -p output=417 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=417 -p output=418 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=418 -p output=419 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=419 -p output=420 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=420 -p output=421 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=421 -p output=422 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=422 -p output=423 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=423 -p output=424 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=424 -p output=425 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=425 -p output=426 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=426 -p output=427 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=427 -p output=428 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=428 -p output=429 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=429 -p output=430 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=430 -p output=431 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=431 -p output=432 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=432 -p output=433 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=433 -p output=434 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=434 -p output=435 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=435 -p output=436 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=436 -p output=437 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=437 -p output=438 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=438 -p output=439 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=439 -p output=440 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=440 -p output=441 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=441 -p output=442 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=442 -p output=443 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=443 -p output=444 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=444 -p output=445 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=445 -p output=446 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=446 -p output=447 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=447 -p output=448 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=448 -p output=449 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=449 -p output=450 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=450 -p output=451 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=451 -p output=452 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=452 -p output=453 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=453 -p output=454 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=454 -p output=455 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=455 -p output=456 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=456 -p output=457 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=457 -p output=458 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=458 -p output=459 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=459 -p output=460 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=460 -p output=461 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=461 -p output=462 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=462 -p output=463 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=463 -p output=464 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=464 -p output=465 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=465 -p output=466 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=466 -p output=467 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=467 -p output=468 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=468 -p output=469 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=469 -p output=470 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=470 -p output=471 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=471 -p output=472 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=472 -p output=473 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=473 -p output=474 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=474 -p output=475 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=475 -p output=476 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=476 -p output=477 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=477 -p output=478 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=478 -p output=479 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=479 -p output=480 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=480 -p output=481 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=481 -p output=482 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=482 -p output=483 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=483 -p output=484 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=484 -p output=485 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=485 -p output=486 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=486 -p output=487 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=487 -p output=488 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=488 -p output=489 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=489 -p output=490 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=490 -p output=491 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=491 -p output=492 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=492 -p output=493 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=493 -p output=494 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=494 -p output=495 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=495 -p output=496 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=496 -p output=497 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=497 -p output=498 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=498 -p output=499 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=499 -p output=500 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=500 -p output=501 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=501 -p output=502 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=502 -p output=503 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=503 -p output=504 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=504 -p output=505 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=505 -p output=506 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=506 -p output=507 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=507 -p output=508 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=508 -p output=509 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=509 -p output=510 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=510 -p output=511 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=511 -p output=512 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=512 -p output=513 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=513 -p output=514 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=514 -p output=515 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=515 -p output=516 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=516 -p output=517 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=517 -p output=518 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=518 -p output=519 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=519 -p output=520 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=520 -p output=521 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=521 -p output=522 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=522 -p output=523 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=523 -p output=524 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=524 -p output=525 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=525 -p output=526 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=526 -p output=527 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=527 -p output=528 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=528 -p output=529 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=529 -p output=530 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=530 -p output=531 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=531 -p output=532 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=532 -p output=533 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=533 -p output=534 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=534 -p output=535 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=535 -p output=536 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=536 -p output=537 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=537 -p output=538 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=538 -p output=539 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=539 -p output=540 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=540 -p output=541 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=541 -p output=542 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=542 -p output=543 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=543 -p output=544 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=544 -p output=545 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=545 -p output=546 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=546 -p output=547 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=547 -p output=548 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=548 -p output=549 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=549 -p output=550 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=550 -p output=551 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=551 -p output=552 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=552 -p output=553 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=553 -p output=554 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=554 -p output=555 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=555 -p output=556 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=556 -p output=557 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=557 -p output=558 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=558 -p output=559 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=559 -p output=560 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=560 -p output=561 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=561 -p output=562 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=562 -p output=563 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=563 -p output=564 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=564 -p output=565 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=565 -p output=566 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=566 -p output=567 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=567 -p output=568 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=568 -p output=569 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=569 -p output=570 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=570 -p output=571 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=571 -p output=572 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=572 -p output=573 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=573 -p output=574 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=574 -p output=575 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=575 -p output=576 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=576 -p output=577 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=577 -p output=578 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=578 -p output=579 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=579 -p output=580 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=580 -p output=581 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=581 -p output=582 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=582 -p output=583 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=583 -p output=584 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=584 -p output=585 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=585 -p output=586 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=586 -p output=587 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=587 -p output=588 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=588 -p output=589 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=589 -p output=590 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=590 -p output=591 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=591 -p output=592 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=592 -p output=593 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=593 -p output=594 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=594 -p output=595 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=595 -p output=596 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=596 -p output=597 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=597 -p output=598 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=598 -p output=599 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=599 -p output=600 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=600 -p output=601 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=601 -p output=602 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=602 -p output=603 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=603 -p output=604 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=604 -p output=605 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=605 -p output=606 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=606 -p output=607 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=607 -p output=608 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=608 -p output=609 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=609 -p output=610 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=610 -p output=611 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=611 -p output=612 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=612 -p output=613 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=613 -p output=614 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=614 -p output=615 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=615 -p output=616 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=616 -p output=617 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=617 -p output=618 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=618 -p output=619 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=619 -p output=620 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=620 -p output=621 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=621 -p output=622 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=622 -p output=623 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=623 -p output=624 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=624 -p output=625 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=625 -p output=626 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=626 -p output=627 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=627 -p output=628 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=628 -p output=629 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=629 -p output=630 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=630 -p output=631 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=631 -p output=632 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=632 -p output=633 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=633 -p output=634 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=634 -p output=635 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=635 -p output=636 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=636 -p output=637 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=637 -p output=638 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=638 -p output=639 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=639 -p output=640 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=640 -p output=641 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=641 -p output=642 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=642 -p output=643 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=643 -p output=644 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=644 -p output=645 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=645 -p output=646 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=646 -p output=647 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=647 -p output=648 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=648 -p output=649 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=649 -p output=650 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=650 -p output=651 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=651 -p output=652 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=652 -p output=653 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=653 -p output=654 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=654 -p output=655 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=655 -p output=656 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=656 -p output=657 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=657 -p output=658 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=658 -p output=659 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=659 -p output=660 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=660 -p output=661 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=661 -p output=662 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=662 -p output=663 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=663 -p output=664 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=664 -p output=665 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=665 -p output=666 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=666 -p output=667 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=667 -p output=668 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=668 -p output=669 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=669 -p output=670 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=670 -p output=671 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=671 -p output=672 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=672 -p output=673 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=673 -p output=674 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=674 -p output=675 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=675 -p output=676 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=676 -p output=677 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=677 -p output=678 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=678 -p output=679 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=679 -p output=680 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=680 -p output=681 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=681 -p output=682 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=682 -p output=683 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=683 -p output=684 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=684 -p output=685 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=685 -p output=686 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=686 -p output=687 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=687 -p output=688 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=688 -p output=689 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=689 -p output=690 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=690 -p output=691 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=691 -p output=692 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=692 -p output=693 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=693 -p output=694 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=694 -p output=695 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=695 -p output=696 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=696 -p output=697 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=697 -p output=698 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=698 -p output=699 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=699 -p output=700 trending.pig
time pig -x local -p root_path=full_unibitrigrams -p input=700 -p output=701 trending.pig
