#!/usr/bin/env bash
time pig -x local -p input=000 -p output=001 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=001 -p output=002 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=002 -p output=003 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=003 -p output=004 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=004 -p output=005 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=005 -p output=006 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=006 -p output=007 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=007 -p output=008 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=008 -p output=009 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=009 -p output=010 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=010 -p output=011 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=011 -p output=012 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=012 -p output=013 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=013 -p output=014 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=014 -p output=015 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=015 -p output=016 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=016 -p output=017 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=017 -p output=018 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=018 -p output=019 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=019 -p output=020 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=020 -p output=021 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=021 -p output=022 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=022 -p output=023 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=023 -p output=024 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=024 -p output=025 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=025 -p output=026 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=026 -p output=027 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=027 -p output=028 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=028 -p output=029 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=029 -p output=030 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=030 -p output=031 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=031 -p output=032 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=032 -p output=033 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=033 -p output=034 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=034 -p output=035 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=035 -p output=036 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=036 -p output=037 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=037 -p output=038 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=038 -p output=039 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=039 -p output=040 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=040 -p output=041 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=041 -p output=042 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=042 -p output=043 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=043 -p output=044 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=044 -p output=045 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=045 -p output=046 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=046 -p output=047 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=047 -p output=048 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=048 -p output=049 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=049 -p output=050 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=050 -p output=051 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=051 -p output=052 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=052 -p output=053 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=053 -p output=054 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=054 -p output=055 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=055 -p output=056 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=056 -p output=057 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=057 -p output=058 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=058 -p output=059 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=059 -p output=060 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=060 -p output=061 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=061 -p output=062 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=062 -p output=063 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=063 -p output=064 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=064 -p output=065 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=065 -p output=066 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=066 -p output=067 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=067 -p output=068 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=068 -p output=069 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=069 -p output=070 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=070 -p output=071 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=071 -p output=072 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=072 -p output=073 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=073 -p output=074 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=074 -p output=075 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=075 -p output=076 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=076 -p output=077 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=077 -p output=078 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=078 -p output=079 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=079 -p output=080 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=080 -p output=081 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=081 -p output=082 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=082 -p output=083 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=083 -p output=084 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=084 -p output=085 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=085 -p output=086 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=086 -p output=087 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=087 -p output=088 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=088 -p output=089 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=089 -p output=090 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=090 -p output=091 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=091 -p output=092 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=092 -p output=093 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=093 -p output=094 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=094 -p output=095 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=095 -p output=096 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=096 -p output=097 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=097 -p output=098 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=098 -p output=099 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=099 -p output=100 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=100 -p output=101 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=101 -p output=102 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=102 -p output=103 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=103 -p output=104 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=104 -p output=105 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=105 -p output=106 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=106 -p output=107 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=107 -p output=108 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=108 -p output=109 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=109 -p output=110 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=110 -p output=111 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=111 -p output=112 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=112 -p output=113 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=113 -p output=114 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=114 -p output=115 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=115 -p output=116 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=116 -p output=117 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=117 -p output=118 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=118 -p output=119 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=119 -p output=120 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=120 -p output=121 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=121 -p output=122 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=122 -p output=123 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=123 -p output=124 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=124 -p output=125 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=125 -p output=126 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=126 -p output=127 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=127 -p output=128 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=128 -p output=129 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=129 -p output=130 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=130 -p output=131 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=131 -p output=132 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=132 -p output=133 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=133 -p output=134 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=134 -p output=135 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=135 -p output=136 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=136 -p output=137 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=137 -p output=138 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=138 -p output=139 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=139 -p output=140 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=140 -p output=141 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=141 -p output=142 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=142 -p output=143 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=143 -p output=144 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=144 -p output=145 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=145 -p output=146 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=146 -p output=147 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=147 -p output=148 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=148 -p output=149 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=149 -p output=150 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=150 -p output=151 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=151 -p output=152 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=152 -p output=153 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=153 -p output=154 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=154 -p output=155 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=155 -p output=156 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=156 -p output=157 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=157 -p output=158 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=158 -p output=159 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=159 -p output=160 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=160 -p output=161 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=161 -p output=162 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=162 -p output=163 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=163 -p output=164 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=164 -p output=165 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=165 -p output=166 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=166 -p output=167 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=167 -p output=168 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=168 -p output=169 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=169 -p output=170 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=170 -p output=171 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=171 -p output=172 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=172 -p output=173 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=173 -p output=174 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=174 -p output=175 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=175 -p output=176 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=176 -p output=177 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=177 -p output=178 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=178 -p output=179 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=179 -p output=180 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=180 -p output=181 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=181 -p output=182 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=182 -p output=183 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=183 -p output=184 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=184 -p output=185 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=185 -p output=186 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=186 -p output=187 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=187 -p output=188 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=188 -p output=189 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=189 -p output=190 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=190 -p output=191 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=191 -p output=192 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=192 -p output=193 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=193 -p output=194 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=194 -p output=195 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=195 -p output=196 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=196 -p output=197 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=197 -p output=198 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=198 -p output=199 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=199 -p output=200 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=200 -p output=201 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=201 -p output=202 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=202 -p output=203 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=203 -p output=204 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=204 -p output=205 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=205 -p output=206 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=206 -p output=207 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=207 -p output=208 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=208 -p output=209 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=209 -p output=210 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=210 -p output=211 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=211 -p output=212 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=212 -p output=213 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=213 -p output=214 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=214 -p output=215 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=215 -p output=216 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=216 -p output=217 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=217 -p output=218 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=218 -p output=219 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=219 -p output=220 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=220 -p output=221 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=221 -p output=222 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=222 -p output=223 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=223 -p output=224 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=224 -p output=225 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=225 -p output=226 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=226 -p output=227 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=227 -p output=228 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=228 -p output=229 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=229 -p output=230 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=230 -p output=231 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=231 -p output=232 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=232 -p output=233 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=233 -p output=234 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=234 -p output=235 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=235 -p output=236 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=236 -p output=237 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=237 -p output=238 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=238 -p output=239 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=239 -p output=240 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=240 -p output=241 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=241 -p output=242 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=242 -p output=243 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=243 -p output=244 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=244 -p output=245 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=245 -p output=246 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=246 -p output=247 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=247 -p output=248 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=248 -p output=249 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=249 -p output=250 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=250 -p output=251 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=251 -p output=252 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=252 -p output=253 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=253 -p output=254 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=254 -p output=255 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=255 -p output=256 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=256 -p output=257 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=257 -p output=258 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=258 -p output=259 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=259 -p output=260 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=260 -p output=261 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=261 -p output=262 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=262 -p output=263 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=263 -p output=264 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=264 -p output=265 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=265 -p output=266 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=266 -p output=267 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=267 -p output=268 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=268 -p output=269 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=269 -p output=270 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=270 -p output=271 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=271 -p output=272 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=272 -p output=273 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=273 -p output=274 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=274 -p output=275 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=275 -p output=276 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=276 -p output=277 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=277 -p output=278 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=278 -p output=279 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=279 -p output=280 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=280 -p output=281 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=281 -p output=282 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=282 -p output=283 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=283 -p output=284 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=284 -p output=285 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=285 -p output=286 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=286 -p output=287 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=287 -p output=288 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=288 -p output=289 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=289 -p output=290 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=290 -p output=291 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=291 -p output=292 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=292 -p output=293 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=293 -p output=294 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=294 -p output=295 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=295 -p output=296 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=296 -p output=297 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=297 -p output=298 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=298 -p output=299 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=299 -p output=300 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=300 -p output=301 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=301 -p output=302 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=302 -p output=303 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=303 -p output=304 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=304 -p output=305 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=305 -p output=306 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=306 -p output=307 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=307 -p output=308 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=308 -p output=309 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=309 -p output=310 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=310 -p output=311 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=311 -p output=312 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=312 -p output=313 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=313 -p output=314 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=314 -p output=315 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=315 -p output=316 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=316 -p output=317 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=317 -p output=318 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=318 -p output=319 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=319 -p output=320 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=320 -p output=321 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=321 -p output=322 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=322 -p output=323 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=323 -p output=324 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=324 -p output=325 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=325 -p output=326 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=326 -p output=327 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=327 -p output=328 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=328 -p output=329 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=329 -p output=330 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=330 -p output=331 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=331 -p output=332 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=332 -p output=333 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=333 -p output=334 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=334 -p output=335 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=335 -p output=336 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=336 -p output=337 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=337 -p output=338 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=338 -p output=339 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=339 -p output=340 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=340 -p output=341 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=341 -p output=342 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=342 -p output=343 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=343 -p output=344 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=344 -p output=345 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=345 -p output=346 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=346 -p output=347 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=347 -p output=348 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=348 -p output=349 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=349 -p output=350 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=350 -p output=351 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=351 -p output=352 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=352 -p output=353 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=353 -p output=354 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=354 -p output=355 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=355 -p output=356 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=356 -p output=357 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=357 -p output=358 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=358 -p output=359 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=359 -p output=360 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=360 -p output=361 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=361 -p output=362 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=362 -p output=363 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=363 -p output=364 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=364 -p output=365 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=365 -p output=366 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=366 -p output=367 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=367 -p output=368 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=368 -p output=369 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=369 -p output=370 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=370 -p output=371 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=371 -p output=372 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=372 -p output=373 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=373 -p output=374 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=374 -p output=375 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=375 -p output=376 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=376 -p output=377 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=377 -p output=378 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=378 -p output=379 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=379 -p output=380 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=380 -p output=381 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=381 -p output=382 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=382 -p output=383 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=383 -p output=384 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=384 -p output=385 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=385 -p output=386 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=386 -p output=387 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=387 -p output=388 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=388 -p output=389 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=389 -p output=390 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=390 -p output=391 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=391 -p output=392 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=392 -p output=393 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=393 -p output=394 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=394 -p output=395 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=395 -p output=396 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=396 -p output=397 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=397 -p output=398 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=398 -p output=399 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=399 -p output=400 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=400 -p output=401 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=401 -p output=402 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=402 -p output=403 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=403 -p output=404 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=404 -p output=405 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=405 -p output=406 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=406 -p output=407 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=407 -p output=408 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=408 -p output=409 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=409 -p output=410 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=410 -p output=411 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=411 -p output=412 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=412 -p output=413 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=413 -p output=414 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=414 -p output=415 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=415 -p output=416 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=416 -p output=417 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=417 -p output=418 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=418 -p output=419 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=419 -p output=420 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=420 -p output=421 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=421 -p output=422 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=422 -p output=423 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=423 -p output=424 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=424 -p output=425 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=425 -p output=426 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=426 -p output=427 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=427 -p output=428 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=428 -p output=429 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=429 -p output=430 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=430 -p output=431 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=431 -p output=432 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=432 -p output=433 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=433 -p output=434 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=434 -p output=435 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=435 -p output=436 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=436 -p output=437 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=437 -p output=438 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=438 -p output=439 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=439 -p output=440 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=440 -p output=441 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=441 -p output=442 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=442 -p output=443 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=443 -p output=444 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=444 -p output=445 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=445 -p output=446 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=446 -p output=447 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=447 -p output=448 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=448 -p output=449 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=449 -p output=450 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=450 -p output=451 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=451 -p output=452 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=452 -p output=453 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=453 -p output=454 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=454 -p output=455 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=455 -p output=456 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=456 -p output=457 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=457 -p output=458 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=458 -p output=459 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=459 -p output=460 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=460 -p output=461 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=461 -p output=462 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=462 -p output=463 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=463 -p output=464 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=464 -p output=465 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=465 -p output=466 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=466 -p output=467 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=467 -p output=468 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=468 -p output=469 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=469 -p output=470 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=470 -p output=471 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=471 -p output=472 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=472 -p output=473 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=473 -p output=474 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=474 -p output=475 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=475 -p output=476 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=476 -p output=477 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=477 -p output=478 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=478 -p output=479 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=479 -p output=480 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=480 -p output=481 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=481 -p output=482 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=482 -p output=483 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=483 -p output=484 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=484 -p output=485 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=485 -p output=486 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=486 -p output=487 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=487 -p output=488 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=488 -p output=489 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=489 -p output=490 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=490 -p output=491 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=491 -p output=492 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=492 -p output=493 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=493 -p output=494 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=494 -p output=495 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=495 -p output=496 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=496 -p output=497 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=497 -p output=498 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=498 -p output=499 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=499 -p output=500 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=500 -p output=501 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=501 -p output=502 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=502 -p output=503 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=503 -p output=504 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=504 -p output=505 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=505 -p output=506 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=506 -p output=507 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=507 -p output=508 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=508 -p output=509 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=509 -p output=510 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=510 -p output=511 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=511 -p output=512 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=512 -p output=513 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=513 -p output=514 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=514 -p output=515 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=515 -p output=516 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=516 -p output=517 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=517 -p output=518 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=518 -p output=519 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=519 -p output=520 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=520 -p output=521 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=521 -p output=522 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=522 -p output=523 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=523 -p output=524 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=524 -p output=525 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=525 -p output=526 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=526 -p output=527 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=527 -p output=528 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=528 -p output=529 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=529 -p output=530 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=530 -p output=531 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=531 -p output=532 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=532 -p output=533 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=533 -p output=534 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=534 -p output=535 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=535 -p output=536 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=536 -p output=537 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=537 -p output=538 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=538 -p output=539 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=539 -p output=540 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=540 -p output=541 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=541 -p output=542 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=542 -p output=543 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=543 -p output=544 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=544 -p output=545 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=545 -p output=546 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=546 -p output=547 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=547 -p output=548 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=548 -p output=549 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=549 -p output=550 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=550 -p output=551 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=551 -p output=552 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=552 -p output=553 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=553 -p output=554 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=554 -p output=555 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=555 -p output=556 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=556 -p output=557 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=557 -p output=558 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=558 -p output=559 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=559 -p output=560 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=560 -p output=561 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=561 -p output=562 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=562 -p output=563 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=563 -p output=564 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=564 -p output=565 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=565 -p output=566 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=566 -p output=567 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=567 -p output=568 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=568 -p output=569 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=569 -p output=570 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=570 -p output=571 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=571 -p output=572 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=572 -p output=573 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=573 -p output=574 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=574 -p output=575 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=575 -p output=576 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=576 -p output=577 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=577 -p output=578 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=578 -p output=579 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=579 -p output=580 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=580 -p output=581 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=581 -p output=582 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=582 -p output=583 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=583 -p output=584 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=584 -p output=585 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=585 -p output=586 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=586 -p output=587 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=587 -p output=588 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=588 -p output=589 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=589 -p output=590 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=590 -p output=591 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=591 -p output=592 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=592 -p output=593 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=593 -p output=594 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=594 -p output=595 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=595 -p output=596 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=596 -p output=597 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=597 -p output=598 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=598 -p output=599 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=599 -p output=600 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=600 -p output=601 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=601 -p output=602 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=602 -p output=603 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=603 -p output=604 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=604 -p output=605 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=605 -p output=606 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=606 -p output=607 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=607 -p output=608 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=608 -p output=609 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=609 -p output=610 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=610 -p output=611 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=611 -p output=612 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=612 -p output=613 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=613 -p output=614 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=614 -p output=615 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=615 -p output=616 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=616 -p output=617 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=617 -p output=618 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=618 -p output=619 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=619 -p output=620 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=620 -p output=621 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=621 -p output=622 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=622 -p output=623 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=623 -p output=624 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=624 -p output=625 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=625 -p output=626 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=626 -p output=627 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=627 -p output=628 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=628 -p output=629 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=629 -p output=630 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=630 -p output=631 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=631 -p output=632 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=632 -p output=633 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=633 -p output=634 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=634 -p output=635 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=635 -p output=636 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=636 -p output=637 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=637 -p output=638 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=638 -p output=639 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=639 -p output=640 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=640 -p output=641 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=641 -p output=642 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=642 -p output=643 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=643 -p output=644 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=644 -p output=645 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=645 -p output=646 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=646 -p output=647 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=647 -p output=648 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=648 -p output=649 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=649 -p output=650 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=650 -p output=651 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=651 -p output=652 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=652 -p output=653 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=653 -p output=654 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=654 -p output=655 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=655 -p output=656 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=656 -p output=657 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=657 -p output=658 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=658 -p output=659 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=659 -p output=660 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=660 -p output=661 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=661 -p output=662 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=662 -p output=663 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=663 -p output=664 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=664 -p output=665 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=665 -p output=666 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=666 -p output=667 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=667 -p output=668 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=668 -p output=669 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=669 -p output=670 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=670 -p output=671 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=671 -p output=672 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=672 -p output=673 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=673 -p output=674 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=674 -p output=675 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=675 -p output=676 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=676 -p output=677 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=677 -p output=678 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=678 -p output=679 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=679 -p output=680 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=680 -p output=681 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=681 -p output=682 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=682 -p output=683 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=683 -p output=684 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=684 -p output=685 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=685 -p output=686 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=686 -p output=687 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=687 -p output=688 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=688 -p output=689 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=689 -p output=690 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=690 -p output=691 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=691 -p output=692 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=692 -p output=693 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=693 -p output=694 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=694 -p output=695 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=695 -p output=696 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=696 -p output=697 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=697 -p output=698 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=698 -p output=699 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=699 -p output=700 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
time pig -x local -p input=700 -p output=701 -p piggybankjar=/home/mat/dev/pig/piggybank.jar trending.pig
